import { ArrowDown, ArrowUp, Trash2 } from 'lucide-react';
import { Button, Input } from '@/components/ui';
import { DateTimeField } from '@/components/form';
import { cn } from '@/lib/utils';
import type { CityRow } from '@/types';

/**
 * Controlled list editor for trip waypoints. Each row carries a city + optional arrival
 * date/time + wait minutes + a notes line. Reorder via ↑/↓ buttons (drag-and-drop deferred);
 * remove via the trash icon. The PostTripPage owns the array; this component only renders + emits.
 *
 * For round-trip the page passes 0+ intermediate stops (rendered as "Stop N") between a pinned
 * origin and turnaround. For multi-way the page passes the full destination list.
 */
export interface WaypointDraft {
  /** Stable local id for React keys + reorder. Generated by the parent on add. */
  uid: string;
  cityId: string;
  /** Local-datetime string (yyyy-MM-ddTHH:mm) — converted to ISO at submit time. */
  arriveAt: string;
  /** Total minutes of waiting at this stop (driver bata × wait_rate_per_min applies). */
  waitMinutes: number;
  notes: string;
}

export interface WaypointEditorProps {
  value: WaypointDraft[];
  onChange: (next: WaypointDraft[]) => void;
  cities: CityRow[];
  /** Heading for each row — "Destination" (multi-way) or "Stop" (round-trip intermediate). */
  rowLabel?: string;
  /** Block remove when count is at this minimum. Defaults to 0 (any row removable). */
  minRows?: number;
  /** Add-button label. Defaults to "Add destination". */
  addLabel?: string;
  className?: string;
}

const newUid = () => `wp-${Math.random().toString(36).slice(2, 9)}`;

export function emptyWaypoint(): WaypointDraft {
  return { uid: newUid(), cityId: '', arriveAt: '', waitMinutes: 0, notes: '' };
}

export function WaypointEditor({
  value,
  onChange,
  cities,
  rowLabel = 'Destination',
  minRows = 0,
  addLabel = 'Add destination',
  className,
}: WaypointEditorProps) {
  function update(i: number, patch: Partial<WaypointDraft>): void {
    const next = value.map((w, idx) => (idx === i ? { ...w, ...patch } : w));
    onChange(next);
  }
  function remove(i: number): void {
    if (value.length <= minRows) return;
    onChange(value.filter((_, idx) => idx !== i));
  }
  function move(i: number, dir: -1 | 1): void {
    const j = i + dir;
    if (j < 0 || j >= value.length) return;
    const next = value.slice();
    [next[i], next[j]] = [next[j]!, next[i]!];
    onChange(next);
  }
  function add(): void {
    onChange([...value, emptyWaypoint()]);
  }

  return (
    <div className={cn('space-y-2', className)}>
      {value.length === 0 ? (
        <p className="text-xs text-secondary">No {rowLabel.toLowerCase()}s yet — add the first one below.</p>
      ) : (
        value.map((w, i) => (
          <div key={w.uid} className="rounded-xl border bg-white p-3 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-semibold uppercase tracking-wide text-secondary">
                {rowLabel} {i + 1}
              </span>
              <div className="flex items-center gap-1">
                <button
                  type="button"
                  onClick={() => move(i, -1)}
                  disabled={i === 0}
                  aria-label={`Move ${rowLabel.toLowerCase()} ${i + 1} up`}
                  className="rounded p-1 text-secondary hover:bg-muted disabled:opacity-30"
                >
                  <ArrowUp className="size-4" />
                </button>
                <button
                  type="button"
                  onClick={() => move(i, 1)}
                  disabled={i === value.length - 1}
                  aria-label={`Move ${rowLabel.toLowerCase()} ${i + 1} down`}
                  className="rounded p-1 text-secondary hover:bg-muted disabled:opacity-30"
                >
                  <ArrowDown className="size-4" />
                </button>
                <button
                  type="button"
                  onClick={() => remove(i)}
                  disabled={value.length <= minRows}
                  aria-label={`Remove ${rowLabel.toLowerCase()} ${i + 1}`}
                  className="rounded p-1 text-red-500 hover:bg-red-50 disabled:opacity-30"
                >
                  <Trash2 className="size-4" />
                </button>
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="block">
                <span className="sr-only">City</span>
                <select
                  value={w.cityId}
                  onChange={(e) => update(i, { cityId: e.target.value })}
                  className="block h-10 w-full rounded-md border border-input bg-white px-3 text-sm"
                  required
                >
                  <option value="">Select a city</option>
                  {cities.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </label>

              <div className="grid grid-cols-2 gap-2">
                <label className="block">
                  <span className="text-[11px] font-medium text-secondary">Arrive at</span>
                  <DateTimeField
                    value={w.arriveAt}
                    onChange={(value) => update(i, { arriveAt: value })}
                  />
                </label>
                <label className="block">
                  <span className="text-[11px] font-medium text-secondary">Wait (minutes)</span>
                  <Input
                    type="number"
                    min={0}
                    inputMode="numeric"
                    value={w.waitMinutes}
                    onChange={(e) => update(i, { waitMinutes: Math.max(0, Number(e.target.value) || 0) })}
                  />
                </label>
              </div>

              <label className="block">
                <span className="text-[11px] font-medium text-secondary">Notes (optional)</span>
                <Input
                  type="text"
                  value={w.notes}
                  onChange={(e) => update(i, { notes: e.target.value })}
                  placeholder="e.g. drop off at the south gate"
                  maxLength={120}
                />
              </label>
            </div>
          </div>
        ))
      )}

      <Button type="button" variant="outline" size="sm" onClick={add} className="w-full">
        + {addLabel}
      </Button>
    </div>
  );
}

export default WaypointEditor;
