import { ArrowDown, ArrowUp, Trash2 } from 'lucide-react';
import { Button, Input } from '@/components/ui';
import { DateTimeField } from '@/components/form';
import { AddressField } from '@/components/location/AddressField';
import { cn } from '@/lib/utils';
import type { CityRow, Place } from '@/types';

/**
 * Controlled list editor for trip stops. Each row carries a location (a curated city in
 * `mode='city'`, or a searched address in `mode='address'`) + optional arrival date/time +
 * wait minutes + a notes line. Reorder via ↑/↓ buttons; remove via the trash icon. The
 * PostTripPage owns the array; this component only renders + emits.
 *
 * Outstation passes city-mode stops ("Stop"); round-trip labels the first one "First stop".
 * Local passes address-mode stops, biased near the pickup.
 */
export interface WaypointDraft {
  /** Stable local id for React keys + reorder. Generated by the parent on add. */
  uid: string;
  cityId: string;
  /** Address-mode only: the searched place id + the resolved Place (for re-render). */
  placeId?: string;
  place?: Place | null;
  /** Local-datetime string (yyyy-MM-ddTHH:mm) — converted to ISO at submit time. */
  arriveAt: string;
  /** Total minutes of waiting at this stop (driver bata × wait_rate_per_min applies). */
  waitMinutes: number;
  notes: string;
}

export interface WaypointEditorProps {
  value: WaypointDraft[];
  onChange: (next: WaypointDraft[]) => void;
  cities: CityRow[];
  /** 'city' (default) renders a curated-city select; 'address' renders an address search. */
  mode?: 'city' | 'address';
  /** Bias the address search toward this point (address mode only). */
  near?: { lat: number; lng: number };
  /** Heading for each row — "Destination" (multi-way) or "Stop" (round-trip intermediate). */
  rowLabel?: string;
  /** Override the first row's label (e.g. "First stop" for a round trip). */
  firstRowLabel?: string;
  /** Block remove when count is at this minimum. Defaults to 0 (any row removable). */
  minRows?: number;
  /** Add-button label. Defaults to "Add destination". */
  addLabel?: string;
  className?: string;
}

const newUid = () => `wp-${Math.random().toString(36).slice(2, 9)}`;

export function emptyWaypoint(): WaypointDraft {
  return { uid: newUid(), cityId: '', placeId: '', place: null, arriveAt: '', waitMinutes: 0, notes: '' };
}

export function WaypointEditor({
  value,
  onChange,
  cities,
  mode = 'city',
  near,
  rowLabel = 'Destination',
  firstRowLabel,
  minRows = 0,
  addLabel = 'Add destination',
  className,
}: WaypointEditorProps) {
  function update(i: number, patch: Partial<WaypointDraft>): void {
    const next = value.map((w, idx) => (idx === i ? { ...w, ...patch } : w));
    onChange(next);
  }
  function remove(i: number): void {
    if (value.length <= minRows) return;
    onChange(value.filter((_, idx) => idx !== i));
  }
  function move(i: number, dir: -1 | 1): void {
    const j = i + dir;
    if (j < 0 || j >= value.length) return;
    const next = value.slice();
    [next[i], next[j]] = [next[j]!, next[i]!];
    onChange(next);
  }
  function add(): void {
    onChange([...value, emptyWaypoint()]);
  }
  const labelFor = (i: number) => (i === 0 && firstRowLabel ? firstRowLabel : `${rowLabel} ${i + 1}`);

  return (
    <div className={cn('space-y-2', className)}>
      {value.length === 0 ? (
        <p className="text-xs text-secondary">No {rowLabel.toLowerCase()}s yet — add the first one below.</p>
      ) : (
        value.map((w, i) => (
          <div key={w.uid} className="rounded-xl border bg-white p-3 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-semibold uppercase tracking-wide text-secondary">
                {labelFor(i)}
              </span>
              <div className="flex items-center gap-1">
                <button
                  type="button"
                  onClick={() => move(i, -1)}
                  disabled={i === 0}
                  aria-label={`Move ${labelFor(i).toLowerCase()} up`}
                  className="rounded p-1 text-secondary hover:bg-muted disabled:opacity-30"
                >
                  <ArrowUp className="size-4" />
                </button>
                <button
                  type="button"
                  onClick={() => move(i, 1)}
                  disabled={i === value.length - 1}
                  aria-label={`Move ${labelFor(i).toLowerCase()} down`}
                  className="rounded p-1 text-secondary hover:bg-muted disabled:opacity-30"
                >
                  <ArrowDown className="size-4" />
                </button>
                <button
                  type="button"
                  onClick={() => remove(i)}
                  disabled={value.length <= minRows}
                  aria-label={`Remove ${labelFor(i).toLowerCase()}`}
                  className="rounded p-1 text-red-500 hover:bg-red-50 disabled:opacity-30"
                >
                  <Trash2 className="size-4" />
                </button>
              </div>
            </div>

            <div className="space-y-1.5">
              {mode === 'address' ? (
                <AddressField
                  value={w.place ?? null}
                  onChange={(p) => update(i, { place: p, placeId: p?.id ?? '' })}
                  near={near}
                  searchLabel="Search this stop"
                />
              ) : (
                <label className="block">
                  <span className="sr-only">City</span>
                  <select
                    value={w.cityId}
                    onChange={(e) => update(i, { cityId: e.target.value })}
                    className="block h-10 w-full rounded-md border border-input bg-white px-3 text-sm"
                    required
                  >
                    <option value="">Select a city</option>
                    {cities.map((c) => (
                      <option key={c.id} value={c.id}>
                        {c.name}
                      </option>
                    ))}
                  </select>
                </label>
              )}

              <div className="grid grid-cols-2 gap-2">
                <label className="block">
                  <span className="text-[11px] font-medium text-secondary">Arrive at</span>
                  <DateTimeField
                    value={w.arriveAt}
                    onChange={(value) => update(i, { arriveAt: value })}
                  />
                </label>
                <label className="block">
                  <span className="text-[11px] font-medium text-secondary">Wait (minutes)</span>
                  <Input
                    type="number"
                    min={0}
                    inputMode="numeric"
                    value={w.waitMinutes}
                    onChange={(e) => update(i, { waitMinutes: Math.max(0, Number(e.target.value) || 0) })}
                  />
                </label>
              </div>

              <label className="block">
                <span className="text-[11px] font-medium text-secondary">Notes (optional)</span>
                <Input
                  type="text"
                  value={w.notes}
                  onChange={(e) => update(i, { notes: e.target.value })}
                  placeholder="e.g. drop off at the south gate"
                  maxLength={120}
                />
              </label>
            </div>
          </div>
        ))
      )}

      <Button type="button" variant="outline" size="sm" onClick={add} className="w-full">
        + {addLabel}
      </Button>
    </div>
  );
}

export default WaypointEditor;
